version: "3.9"
services:
  postgres:
    image: postgres:15.1
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - 5432:5432
  app:
    depends_on:
      - postgres
    env_file:
      - ./.env
    build: .
    ports:
      - $PORT:$PORT
    image: linux-forum
